version: 2.1
orbs:
  common: townerhale/tbp-orb-test@dev:alpha
  orb-tools: circleci/orb-tools@11

filters: &filters
  tags:
    only: /.*/

jobs:
  basic-test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Verify orb loaded
          command: echo "Orb loaded successfully"

workflows:
  test-deploy:
    jobs:
      - basic-test:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: townerhale/tbp-orb-test
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - basic-test
          context:
            - orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
