version: 2.1
orbs:
  common: townerhale/tbp-orb-test@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11
filters: &filters
  tags:
    only: /.*/
jobs:
  # Define one or more jobs which will utilize your orb's commands and parameters to validate your changes.
  command-tests:
    executor: common/default
    steps:
      - checkout
      - common/add-github-commiter
      - common/terraform-install
      - common/yq-install
      - common/cosign-install
      - common/coverage
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - common/pr-lint:
          filters: *filters
          context:
            - GITHUB
            - LINEAR_APP
      - command-tests:
          filters: *filters
          context: GITHUB
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: townerhale/tbp-orb-test
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context:
            - orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
      - common/semantic-release:
          name: semantic-release
          npm: true
          github: true
          dry-run: false
          context:
            - GITHUB
            - NPM
            - SLACK
          filters:
            branches:
              only: main
