version: 2.1
orbs:
  common: townerhale/tbp-orb-test@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11

filters: &filters
  tags:
    only: /.*/

jobs:
  command-tests:
    executor: common/default
    steps:
      - checkout
      - common/add-github-commiter
      - common/terraform-install
      - common/yq-install
      - common/cosign-install
      - common/coverage

workflows:
  test-deploy:
    jobs:
      - common/pr-lint:
          filters: *filters
          context:
            - GITHUB
      - command-tests:
          filters: *filters
          context: GITHUB
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: townerhale/tbp-orb-test
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context:
            - orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
